# -*- coding: utf-8 -*-
"""Intro_to_Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAx3h2RLsjSoBGWAR7-1SnK9Ccl5WTlQ
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

from google.colab import files
uploads= files.upload()

data=pd.read_csv('Nairobi Office Price Ex.csv')

data.head(2)

nominal=['LOC','FUR','WATER','HK_SER']
ordinal=['AMB','PROX_SCH','PROX_ROAD','PROX_MALL']
numerical=['SIZE']
target=['PRICE']

for feature in ordinal:
  value=data[feature]
  encoder=LabelEncoder()
  trans_f=encoder.fit_transform(value)
  data[feature]=trans_f

data

pd.get_dummies(data[nominal])

final_data=pd.concat([new_data,data],axis=1)
final_data.drop(nominal,axis=1,inplace=True)

final_data.head(2)